[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer-when-downgrade"
Content-Security-Policy = "frame-ancestors 'none'; default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self';"

[[headers]]
for = "/*"
[headers.values]
X-Content-Type-Options = "nosniff"

[build]
command = “CI=false npm run build”